INSERT INTO competitions (rank, sport, year, country) VALUES
('European Championship', 'Football', 2020, 'Europe'),
('World Championship', 'Hockey', 2018, 'Russia'),
('Olympic Games', 'Basketball', 2016, 'Brazil'),
('World Championship', 'Boxing', 2021, 'Russia'),
('World Cup', 'Football', 2019, 'China'),
('European Championship', 'Tennis', 2022, 'Italy'),
('Olympic Games', 'Swimming', 2020, 'Japan'),
('World Championship', 'Basketball', 2019, 'China'),
('European Championship', 'Hockey', 2021, 'Belarus'),
('World Cup', 'Hockey', 2018, 'Russia'),
('World Championship', 'Football', 2014, 'Brazil'),
('Olympic Games', 'Athletics', 2016, 'Brazil'),
('European Championship', 'Basketball', 2017, 'Turkey'),
('World Championship', 'Tennis', 2020, 'France'),
('Olympic Games', 'Boxing', 2021, 'Japan'),
('European Championship', 'Football', 2012, 'Poland'),
('World Cup', 'Basketball', 2019, 'China'),
('World Championship', 'Athletics', 2019, 'Qatar'),
('Olympic Games', 'Hockey', 2018, 'South Korea'),
('European Championship', 'Boxing', 2020, 'Ukraine');

INSERT INTO teams (name, country) VALUES
('Spartak', 'Russia'),
('Dynamo', 'Russia'),
('Lokomotiv', 'Russia'),
('Barcelona', 'Spain'),
('Real Madrid', 'Spain'),
('Manchester United', 'England'),
('CSKA', 'Russia'),
('Zenit', 'Russia'),
('PSG', 'France'),
('Bayern Munich', 'Germany'),
('Manchester City', 'England'),
('Juventus', 'Italy'),
('Liverpool', 'England'),
('Arsenal', 'England'),
('Dynamo Kiev', 'Ukraine'),
('Shakhtar', 'Ukraine'),
('Barcelona', 'Spain'),
('Real Madrid', 'Spain'),
('Milan', 'Italy'),
('Inter', 'Italy');

INSERT INTO competition_results (competition_id, team_id, opponent_team, result_type) VALUES
(1, 1, 'Dynamo', 'Win'),
(1, 2, 'Lokomotiv', 'Loss'),
(1, 3, 'Spartak', 'Draw'),
(2, 1, 'Real Madrid', 'Loss'),
(2, 2, 'Manchester United', 'Win'),
(2, 3, 'Lokomotiv', 'Draw'),
(3, 1, 'Barcelona', 'Draw'),
(3, 2, 'Real Madrid', 'Loss'),
(3, 3, 'Manchester United', 'Win'),
(4, 4, 'Red corner', 'Win'),
(4, 5, 'White corner', 'Loss'),
(4, 6, 'Blue corner', 'Draw'),
(5, 7, 'Liverpool', 'Loss'),
(5, 8, 'Manchester City', 'Win'),
(5, 9, 'Bayern Munich', 'Draw'),
(6, 10, 'Juventus', 'Win'),
(6, 11, 'Milan', 'Loss'),
(6, 12, 'Inter', 'Draw'),
(7, 13, 'Dynamo Kiev', 'Win'),
(7, 14, 'Shakhtar', 'Loss'),
(7, 15, 'Zenit', 'Draw'),
(8, 16, 'France', 'Win'),
(8, 17, 'USA', 'Loss'),
(8, 18, 'Argentina', 'Draw'),
(9, 19, 'Russia', 'Loss'),
(9, 20, 'Canada', 'Win'),
(9, 3, 'Spartak', 'Draw'),
(10, 1, 'Dynamo', 'Loss'),
(10, 2, 'Lokomotiv', 'Win'),
(10, 3, 'Spartak', 'Draw');